### ISSUE TITLE
[Guide] Send an encrypted message

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#113]
The next SDK release enables message [encryption](https://github.com/nemtech/nem2-sdk-typescript-javascript/commit/c513cc5369cfae7981e31c45326971df23aa9c01).

Create a guide explaining how to send a transfer transaction using an encrypted message, and how the recipient can decrypt it.

## Deliverable

* Guide and code example

## Resources

* [How to write a guide](https://nemtech.github.io/guidelines/writing-a-guide.html)

**Comment by wzulfikar** [comment]
Hi @dgarcia360, is the relationship between `encryptMessage` and `decryptMessage` intentionally symmetric ([Account.ts#L90-L102](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/0123530b9e424aeb2c60ac6d43564e649f9eee5f/src/model/account/Account.ts#L90-L102))? 

![Screen Shot 2019-04-26 at 9 21 50 PM](https://user-images.githubusercontent.com/7823011/56815191-e63b9f80-686a-11e9-9f41-bef92dc4bf02.png)

I thought we're supposed to pass `senderPublicAccount`, instead of `recipientPublicAccount` (line 100). This is based on my understanding on how the `crypto.decode` works, which is used by above encrypt/decrypt methods behind the scene.

`crypto.encode()` ([crypto.js#L278](https://github.com/nemtech/nem2-library-js/blob/d03786626e995cfa0a3e3f4e7321d632e1dca6cf/src/crypto/crypto.js#L278)):
![Screen Shot 2019-04-26 at 9 30 50 PM](https://user-images.githubusercontent.com/7823011/56815048-98bf3280-686a-11e9-8d92-3f3303fbf548.png)

`crypto.decode()` ([crypto.js#L301](https://github.com/nemtech/nem2-library-js/blob/d03786626e995cfa0a3e3f4e7321d632e1dca6cf/src/crypto/crypto.js#L301)):
![Screen Shot 2019-04-26 at 9 29 11 PM](https://user-images.githubusercontent.com/7823011/56814950-5f86c280-686a-11e9-90f2-6132aa6daeb5.png)

**Comment by dgarcia360** [comment]
Hi @wzulfikar, thanks for raising the issue.

As it suggests an SDK change, we can continue the discussion here https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/132 We will take into account the issue resolution when writing this guide for the docs.

**Comment by wzulfikar** [comment]
Roger that 👌
