### ISSUE TITLE
The mosaic supply range needs updating.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/nem2-docs#177]
For mosaic supply range in the current documentation needs to change from 9,000,000,000 to 9'000'000'000'000'000 - "Indicates the amount of mosaic in circulation. The total supply must be in the range of 0 and 9,000,000,000."

**Comment by dgarcia360** [comment]
I think ``maxMosaicAtomicUnits = 9'000'000'000'000'000`` refers to the absolute amount. 

If we take into account divisibility (6), the relative max amount is ``9,000,000,000''.

**Comment by Wayonb** [comment]
@dgarcia360 That's what I thought also but I tested with both divisibility 0 and 6 and it didn't make any difference. See the txs below.  There might be a bug in the code since it is not taken divisibility into account here.

http://c2.nem.ninja/#/aggregate/5D122CA74B404F000103C3E2
http://c2.nem.ninja/#/mosaicSupply/5D122D3F4B404F000103C3FD

**Comment by dgarcia360** [comment]
The transaction seems ok to me. The mosaic has gained a supply 9000000020 (absolute), which is smaller than 9'000'000'000'000'000.

In relative terms, it is not out of limits:

> relativeAmount = absoluteAmount / 10^divisibility = 9000000020 / 10^6 =  9,000.000020

We can change the docs adding " 9'000'000'000'000'000" instead of 9,000,000,000, making clear that is expressed in absolute terms. In this case, we can make the value also valid if someone decides to use a mosaic divisibility different to 6.

**Comment by Wayonb** [comment]
Yea I think it is always absolute check. Below is the same txs with divisibility set to 0.

http://c2.nem.ninja/#/aggregate/5D1243474B404F000103C72C
http://c2.nem.ninja/#/mosaicSupply/5D1243534B404F000103C736
