### ISSUE TITLE
PersistentDelegationRequestTransaction

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-docs#293]
PersistentDelegationRequestTransaction shown in the docs is the old format.
`PersistentDelegationRequestTransaction.create`
instead of
`PersistentDelegationRequestTransaction.createPersistentDelegationRequestTransaction`

Also, [the link at point 3](https://nemtech.github.io/guides/accountlink/activating-delegated-harvesting.html) on PersistentDelegationRequestTransaction points to https://nemtech.github.io/concepts/transfer-transaction.html. Not sure whether it is the wanted behaviour.

**Comment by dgarcia360** [comment]
Thanks @decentraliser for opening the issue!

> PersistentDelegationRequestTransaction shown in the docs is the old format.

Fixed here https://github.com/nemtech/nem2-docs/commit/9f19ddcfe04b0d21ecf182e7bf52ac9497266fe3


> Also, the link at point 3 on PersistentDelegationRequestTransaction points to https://nemtech.github.io/concepts/transfer-transaction.html. Not sure whether it is the wanted behaviour.

It's intended, because ``PersistentDelegationRequestTransaction`` extend from [TransferTransaction](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/dc6135d/src/model/transaction/PersistentDelegationRequestTransaction.ts#L36).
