### ISSUE TITLE
Add model schema in guides

### ISSUE THREAD

**Issue by daoka** [nemtech/nem2-docs#47]
I wrote catapult model schema from catapult-rest source code.

https://hackmd.io/etx3lsvyQPm6xneF5gUS8A

If there need it, I'll add this article to guide.
what do you think?

**Comment by dgarcia360** [comment]
Thanks @daoka for your contribution!

Currently, we are missing most of the model schemas that you provided in the current documentation. 

Instead of linking it as a guide, I think it would be more consistent if we copy each schema to the "built-in feature / protocol" section where it belongs. 

What do you think ? If you want, you can apply directly the changes by submitting a pull-request. On the other hand, if you don't have the time I can create a new branch, organize the model schemas in each document and add you as a co-author of each commit improvement.

**Comment by daoka** [comment]
> Instead of linking it as a guide, I think it would be more consistent if we copy each schema to the "built-in feature / protocol" section where it belongs.

It's a good idea.
I'll add each schema to the "built-in feature / protocol" and submit a pull request.
