### ISSUE TITLE
[Concept] Block score

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-docs#72]
Add a complete description for the block score.

* https://nemtech.github.io/endpoints.html#operation/getBlockchainScore
* https://nem.io/wp-content/themes/nem/files/NEM_techRef.pdf

**Comment by kyleqchain** [comment]
@dgarcia360 I am preparing to tackle this issue, but the 1st link in the description appears broken. Can you clarify its significance? Thanks!

**Comment by dgarcia360** [comment]
Link updated!

**Comment by kyleqchain** [comment]
@dgarcia360 In order to edit https://nemtech.github.io/endpoints.html#operation/getBlockchainScore do I need to fork nemtech/nemtech.github.io? From GitHub search, I see 5 files that match the content to be edited: _downloads/swagger.yaml, ja/_downloads/swagger.yaml, _sources/cli.rst.txt, ja/_sources/cli.rst.txt, and cli.html. All of which are in nemtech/nemtech.github.io. Would I need to update each of these files for the changes to be consistent?

**Comment by dgarcia360** [comment]
@kyleqchain Have missed this message here but already have answered the question in private.

PR merged 👍 https://github.com/nemtech/nem2-docs/pull/88#pullrequestreview-211131379
